#' Raw Rusa unicolor occurrence data
#'
#' A dataset containing the raw, unthinned occurrence records for Rusa unicolor
#' (Sambar deer) in Thailand. This dataset is used to demonstrate the spatial
#' clustering and environmental bias present in typical SDM datasets.
#'
#' @format A data frame with occurrence coordinates:
#' \describe{
#'   \item{species}{The species name}
#'   \item{x}{Longitude coordinates in decimal degrees}
#'   \item{y}{Latitude coordinates in decimal degrees}
#' }
#' @source Example dataset provided with the bean package.
"occ_data_raw"

#' Prepared occurrence data
#'
#' A dataset containing the cleaned and scaled occurrence records ready for
#' environmental thinning. Missing coordinates and points outside the raster
#' extent have been removed, and environmental data has been extracted.
#'
#' @format A data frame containing coordinates and environmental variables:
#' \describe{
#'   \item{species}{The species name}
#'   \item{x}{Longitude coordinates}
#'   \item{y}{Latitude coordinates}
#'   \item{bio_1}{Scaled Annual Mean Temperature}
#'   \item{bio_4}{Scaled Temperature Seasonality}
#'   \item{bio_12}{Scaled Annual Precipitation}
#'   \item{bio_15}{Scaled Precipitation Seasonality}
#' }
"origin_dat_prepared"

#' Stochastic thinned environmental data
#'
#' The output object generated by running \code{\link{thin_env_nd}} on the
#' prepared occurrence data. It contains exactly one randomly selected point
#' per occupied environmental grid cell.
#'
#' @format An object of class \code{bean_thinned_density} containing:
#' \describe{
#'   \item{thinned_data}{A data frame of the retained occurrence points}
#'   \item{n_original}{The number of points before thinning}
#'   \item{n_thinned}{The number of points after thinning}
#'   \item{parameters}{The thinning parameters used}
#' }
"thinned_stochastic"

#' Deterministic thinned environmental data
#'
#' The output object generated by running \code{\link{thin_env_center}} on the
#' prepared occurrence data. It contains a single calculated centroid coordinate
#' for each occupied environmental grid cell.
#'
#' @format An object of class \code{bean_thinned_center} containing:
#' \describe{
#'   \item{thinned_points}{A data frame of the new geometric center points}
#'   \item{n_original}{The number of points before thinning}
#'   \item{n_thinned}{The number of unique grid cells occupied}
#'   \item{parameters}{The thinning parameters used}
#' }
"thinned_deterministic"

#' Fitted origin ellipsoid
#'
#' A multidimensional ellipsoid fitted to the unthinned, prepared occurrence data
#' representing the baseline environmental niche of the species.
#'
#' @format An object of class \code{bean_ellipsoid} containing:
#' \describe{
#'   \item{centroid}{The multidimensional mean of the environmental variables}
#'   \item{covariance_matrix}{The covariance matrix of the variables}
#'   \item{volume}{The hypervolume of the fitted ellipsoid}
#'   \item{parameters}{Model parameters including the confidence level (e.g., 0.95)}
#' }
"origin_ellipse"
