utils::globalVariables(c('env_cell_id',
                         'n',
                         'thinned_count',
                         'difference',
                         '.data',
                         'Status',
                         'y',
                         'auc',
                         'density',
                         'cap',
                         'distances',
                         'resolution',
                         'sd',
                         'median',
                         'center_x',
                         'center_y',
                         'env_cell_id'

))
