# In .github/workflows/R-CMD-check.yaml
# This file should ONLY be responsible for running R CMD check.

on:
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check

permissions:
  contents: read

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,     r: 'release'}
          - {os: windows-latest,   r: 'release'}
          - {os: ubuntu-latest,    r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,    r: 'release'}
          - {os: ubuntu-latest,    r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      # ADDITION 1: Install system dependencies for rgl on Linux
      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libglu1-mesa-dev xvfb

      # ADDITION 2: Start virtual display (Xvfb) on Linux
      - name: Start Xvfb
        if: runner.os == 'Linux'
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Register Java with R
        if: runner.os != 'Windows'
        run: sudo R CMD javareconf
        shell: bash

      # ADDITION 3: Set DISPLAY for dependency installation on Linux
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check
        env:
          DISPLAY: ':99'

      # ADDITION 4: Set DISPLAY for the main check on Linux
      - name: Check R package
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
        env:
          DISPLAY: ':99'
