# In .github/workflows/test-coverage.yaml
# This file is ONLY for calculating test coverage and uploading to Codecov.

on:
  push:
    branches: [main, master]
  pull_request:

name: test-coverage

permissions:
  contents: read

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Register Java with R
        run: sudo R CMD javareconf
        shell: bash

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::covr
            any::xml2
          needs: coverage

      - name: Calculate test coverage
        run: covr::codecov()
        shell: Rscript {0}
